// <auto-generated />
using System;
using System.Collections.Generic;
using DuelApp.Modules.Questions.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuelApp.Modules.Questions.Infrastructure.EF.Migrations
{
    [DbContext(typeof(QuestionsDbContext))]
    [Migration("20260802173720_AddUnpublishedQuestions")]
    partial class AddUnpublishedQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Questions")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("answers", "Questions");
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("AnswerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("questions", "Questions");
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.QuestionImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobETag")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ProcessedQuestionsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RejectedQuestionsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Uploaded");

                    b.Property<int>("TotalQuestionsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("BlobName", "BlobETag")
                        .IsUnique();

                    b.HasIndex("RequestedBy", "CreatedAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("question_imports", "Questions", t =>
                        {
                            t.HasCheckConstraint("CK_question_imports_counts_non_negative", "\"TotalQuestionsCount\" >= 0\r\nAND \"ProcessedQuestionsCount\" >= 0\r\nAND \"RejectedQuestionsCount\" >= 0");
                        });
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.UnpublishedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("SourcePosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("UnpublishedQuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnpublishedQuestionId", "SourcePosition")
                        .IsUnique();

                    b.ToTable("unpublished_answers", "Questions", t =>
                        {
                            t.HasCheckConstraint("CK_unpublished_answers_content_not_blank", "length(btrim(\"Content\")) > 0");

                            t.HasCheckConstraint("CK_unpublished_answers_source_position_non_negative", "\"SourcePosition\" >= 0");
                        });
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.UnpublishedQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("AnswerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("QuestionImportId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePosition")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionImportId", "SourcePosition")
                        .IsUnique();

                    b.ToTable("unpublished_questions", "Questions", t =>
                        {
                            t.HasCheckConstraint("CK_unpublished_questions_source_position_non_negative", "\"SourcePosition\" >= 0");

                            t.HasCheckConstraint("CK_unpublished_questions_title_not_blank", "length(btrim(\"Title\")) > 0");
                        });
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.Answer", b =>
                {
                    b.HasOne("DuelApp.Modules.Questions.Domain.Questions.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.UnpublishedAnswer", b =>
                {
                    b.HasOne("DuelApp.Modules.Questions.Domain.Questions.Entities.UnpublishedQuestion", "UnpublishedQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("UnpublishedQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnpublishedQuestion");
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.UnpublishedQuestion", b =>
                {
                    b.HasOne("DuelApp.Modules.Questions.Domain.Questions.Entities.QuestionImport", "QuestionImport")
                        .WithMany("UnpublishedQuestions")
                        .HasForeignKey("QuestionImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionImport");
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.QuestionImport", b =>
                {
                    b.Navigation("UnpublishedQuestions");
                });

            modelBuilder.Entity("DuelApp.Modules.Questions.Domain.Questions.Entities.UnpublishedQuestion", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
