// <auto-generated />
using System;
using DuelApp.Modules.Duels.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuelApp.Modules.Duels.Infrastructure.EF.Migrations
{
    [DbContext(typeof(DuelsDbContext))]
    [Migration("20260306175140_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Duels")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuelApp.Modules.Duels.Domain.Duels.Entities.Duel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerOneId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerOneScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerTwoId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerTwoScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerOneId", "Status");

                    b.HasIndex("PlayerTwoId", "Status");

                    b.ToTable("Duels", "Duels");
                });

            modelBuilder.Entity("DuelApp.Modules.Duels.Domain.Duels.Entities.Duel", b =>
                {
                    b.OwnsMany("DuelApp.Modules.Duels.Domain.Duels.ValueObjects.DuelRound", "Rounds", b1 =>
                        {
                            b1.Property<Guid>("DuelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Number")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Number"));

                            b1.Property<bool?>("HasPlayerOneAnsweredCorrectly")
                                .HasColumnType("boolean");

                            b1.Property<bool?>("HasPlayerTwoAnsweredCorrectly")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.HasKey("DuelId", "Number");

                            b1.ToTable("DuelRounds", "Duels");

                            b1.WithOwner()
                                .HasForeignKey("DuelId");
                        });

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
