services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: app_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --location /data --skipApiVersionCheck
    ports:
      - "127.0.0.1:10000:10000"
    volumes:
      - azurite_data:/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: servicebus_mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LocalServiceBusPassword_2026!"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus_emulator
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LocalServiceBusPassword_2026!"
      SQL_SERVER: mssql
    ports:
      - "127.0.0.1:5300:5300"
      - "127.0.0.1:5672:5672"
    volumes:
      - ./servicebus-emulator/config.json:/ServiceBus_Emulator/ConfigFiles/Config.json:ro
    depends_on:
      - mssql

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  azurite_data:
